### ISSUE TITLE
Annotator openie: Unable to load clause splitter model

### ISSUE THREAD

**Issue by kuserich** [stanfordnlp/CoreNLP#104]
When using the openie annotator I get three exceptions: 

```
Loading clause searcher from edu/stanford/nlp/models/naturalli/clauseSearcherModel.ser.gz...java.io.IOException: unexpected exception type
	at java.io.ObjectStreamClass.throwMiscException(ObjectStreamClass.java:1538)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1110)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1810)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at edu.stanford.nlp.io.IOUtils.readObjectFromURLOrClasspathOrFileSystem(IOUtils.java:318)
	at edu.stanford.nlp.naturalli.ClauseSplitter.load(ClauseSplitter.java:283)
	at edu.stanford.nlp.naturalli.OpenIE.<init>(OpenIE.java:191)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.openie(AnnotatorImplementations.java:268)
	at edu.stanford.nlp.pipeline.AnnotatorFactories$20.create(AnnotatorFactories.java:644)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:85)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:357)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:130)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:126)
	at pipeline.TestClass.main(TestClass.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.NoSuchMethodException: edu.stanford.nlp.naturalli.ClauseSplitterSearchProblem.$deserializeLambda$(java.lang.invoke.SerializedLambda)
	at java.lang.Class.getDeclaredMethod(Class.java:2117)
	at java.lang.invoke.SerializedLambda$1.run(SerializedLambda.java:224)
	at java.lang.invoke.SerializedLambda$1.run(SerializedLambda.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1104)
	... 22 more
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Could not load clause splitter model at edu/stanford/nlp/models/naturalli/clauseSearcherModel.ser.gz: class java.io.IOException: unexpected exception type
	at edu.stanford.nlp.naturalli.OpenIE.<init>(OpenIE.java:196)
	at edu.stanford.nlp.pipeline.AnnotatorImplementations.openie(AnnotatorImplementations.java:268)
	at edu.stanford.nlp.pipeline.AnnotatorFactories$20.create(AnnotatorFactories.java:644)
	at edu.stanford.nlp.pipeline.AnnotatorPool.get(AnnotatorPool.java:85)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.construct(StanfordCoreNLP.java:357)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:130)
	at edu.stanford.nlp.pipeline.StanfordCoreNLP.<init>(StanfordCoreNLP.java:126)
	at pipeline.TestClass.main(TestClass.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

it seems that somehow when loading the clauseSearchModel.ser.gz java cannot find the method to deserialize.

Unfortunately I am not familiar with Lambdas and days of painful googling didn't get me anywhere. Any help is appreciated.

**Comment by gangeli** [comment]
I've never seen this one before... How are you invoking Java? The common problem is when you have one version of the code, and another version of the models. It may be worthwhile to re-download the code + models, and see if that fixes it.

These issues in general should be resolved in the next CoreNLP release, which should be coming soon!

**Comment by kuserich** [comment]
Yes, I just tried re-downloading the code & models. Unfortunately this doesn't solve the issue.

I am using the source files, **this problem does not occur when using the .jar library**. I downloaded the sources from this repository, added the models, created a new project and ran this piece of code:

```
        Properties properties = new Properties();
        properties.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,depparse,natlog,openie, parse, dcoref,relation,entitymentions");

        StanfordCoreNLP pipeline = new StanfordCoreNLP(properties);
        Annotation annotation = new Annotation("Tim Cook is the CEO of Apple, he replaced Steve Jobs, who died in 2011.");
        pipeline.annotate(annotation);
```

That's it.

You should be able to reconstruct the problem with this information.

**Comment by gangeli** [comment]
I tried replicating the problem from the latest source, and could not. I've re-built the jars, which may help bring the source jar and the model jar in sync (or at least up to date), but the code in the repo alongside the most recent models should always work. Is there a classpath error in your IDE?

**Comment by gangeli** [comment]
My invocation is:

`java -cp classes:.:stanford-corenlp-models-current.jar:lib/slf4j-api.jar:lib/slf4j-api.jar Foo`

With Foo.java:

```java
import java.util.*;
import edu.stanford.nlp.pipeline.*;

class Foo {
  public static void main(String[] args) {
    Properties properties = new Properties();
    properties.setProperty("annotators", "tokenize,ssplit,pos,lemma,ner,depparse,natlog,openie, parse, dcoref,relation,entitymentions");

    StanfordCoreNLP pipeline = new StanfordCoreNLP(properties);
    Annotation annotation = new Annotation("Tim Cook is the CEO of Apple, he replaced Steve Jobs, who died in 2011.");
    pipeline.annotate(annotation);
  }
}
```

**Comment by kuserich** [comment]
I just re-downloaded the source code and the models again and it now works (magic).

This time I ran across a different (small) problem. When I run the example code with the .properties file provided (edu/stanford/nlp/pipeline/StanfordCoreNLP.properties) it uses the annotator *coref* which then fails to open *edu/stanford/nlp/models/hcoref/md-model.ser*.

I always downloaded the sources from your webpage, once for the *Stanford CoreNLP full* and once for the *OpenIE*. Is there some link, where you provide *all* models at once?

**Comment by gangeli** [comment]
Yes, it's hidden on our Github README: http://nlp.stanford.edu/software/stanford-corenlp-models-current.jar

You should be able to use the Github code and the models in the link above, and if the code is not broken (which it sometimes is!) it should work.

**Comment by kuserich** [comment]
Great!

Thank you very much and I apologize for any inconvenience caused.

**Comment by XiaohuanIT** [comment]
This issue occurs when I use the whole source code of openie to build a new java project. And I have searched the code for whole 3 days. In this period, I discovered the process of running by using the eclipse debug mode, and I step into every function. But I did't solve the issue by using the whole openie souce code. Then, I saw the website for http://stanfordnlp.github.io/CoreNLP/openie.html. I build a new java project, and only use the OpenIEDemo.java to test the function. I was excited to see the result is OK, which is no error. So when you occur this issue, you can try to build a java project only by OpenIEDemo.java. Good luck to you.

**Comment by kuserich** [comment]
Thank you for investing your time and sharing your findings. The issue that I had could be resolved by re-downloading the source and models.
